ESM Version
silvenon/remark-smartypants pull request #66
Opened 2021-11-20 20:31 UTC by JuanM04

Given that all the dependencies of this package have become ESM only, it may be appropriate to release a v2.0 as ESM only too

2021-11-20 20:59 UTC, silvenon requested changes
Very cool of you, thanks! 💯

Could you also add the following to `engines` in `package.json`?

```json
"node": "^12.20.0 || ^14.13.1 || >=16.0.0"
```

As recommended by Sindre Sorhus' [ESM migration guide](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).

Also, could you please make a sanity check whether it works as a package? You can do it with [yalc](https://github.com/wclr/yalc), install it globally, then in this project run `yalc publish` (acts as `npm publish`), and in your test project run `yalc add @silvenon/remark-smartypants` (like `npm install`). Then try to use it and let me know if it works 🤞 thanks again very much!

2021-11-20 20:59 UTC, silvenon commented on package.json
>    "main": "index.js",
The guide also recommends replacing `main` to `exports`.
```suggestion
  "exports": "./index.js",
```

2021-11-20 21:51 UTC, JuanM04 commented
> Also, could you please make a sanity check whether it works as a package?

I tested it with astro.build and works perfectly.

Also, I added JSDocs and TypeScript definitions

2021-11-21 00:58 UTC, silvenon approved these changes
Niiiiice! 🥇 🚀

2021-11-21 01:06 UTC, merged

2021-11-21 01:28 UTC, silvenon commented
Published!