Update readme
silvenon/remark-smartypants pull request #68
Opened 2022-01-03 21:01 UTC by grikomsn

This PR polishes up the readme which initially attempt to fix a typo. Merge is optional. ✌🏻

2022-01-03 23:36 UTC, silvenon requested changes
Thank you very much! I have minor suggestions and questions. 🙂

2022-01-03 23:36 UTC, silvenon commented on readme.md
> +[![dt](https://badgen.net/npm/dt/remark-smartypants)][npm]
Not sure if it makes sense to add this text considering that the most important piece of information is missing (which version and how many downloads). Alternatively leave the alt text out completely.

```suggestion
[![package version](https://badgen.net/npm/v/remark-smartypants)][npm]
[![number of downloads](https://badgen.net/npm/dt/remark-smartypants)][npm]
```

2022-01-03 23:36 UTC, silvenon commented on readme.md
> +    //
Did you mean to put something here?

2022-01-03 23:36 UTC, silvenon commented on readme.md
> +import smartypants from "remark-smartypants";
It seems like you have a Prettier extension that's formatting this, could you either turn it off or set it to single quotes and no semicolons?

2022-01-04 16:09 UTC, grikomsn commented
Force pushed with only needed changes. Apologies for the unnecessary commits.

2022-01-05 00:42 UTC, silvenon commented
No problem, thank you so much!

2022-01-05 00:42 UTC, silvenon approved these changes

2022-01-05 00:43 UTC, merged